name: Test Python HASI

on: [push,pull_request]

env:
  hasi-testing-data-ipfs-cid: bafybeihvca4e6ik3twyz5qdz3f33woqpzorrcfwkh47tp3wwpxuuggmbey

jobs:
  test-python-hasi-package:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-10.15]
        include:
          - os: ubuntu-22.04
          - os: windows-2022
          - os: macos-10.15

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Setup ipfs
      uses: ibnesayeed/setup-ipfs@master
      with:
        ipfs_version: ^0.8

    - name: Pin ipfs testing data locally
      run: |
        ipfs pin add -- ${{ env.hasi-testing-data-ipfs-cid }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install itk==5.4.0
        python -m pip install itk-shape==0.4.0
        python -m pip install dwd==1.0.5
        python -m pip install seaborn
        python -m pip install matplotlib
        python -m pip install pytest
        python -m pip install pytest-dependency
        python -m pip install ipfsspec xarray zarr

    - name: Test with pytest
      run: |
        cd src/hasi
        pytest .
